### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by PerWiklander** [jDramaix/gwtmodernizr#1]
This project looks like it is lagging a little from the latest Modernizr ;-)

I might be interested in contributing a bit. Could you give me an idea of the amount of work to port new Modernizr functions?

Did you have some sort of generator to get stub impls from the Modernizr JS?

**Comment by joelhandwell** [comment]
@jDramaix @PerWiklander is there anything update about this?

**Comment by PerWiklander** [comment]
I never heard more in this. And now I haven't touch GWT in a few years either (it's all scalajs + react these days).
